deployment:
  tasks:
    - export DEPLOYPATH=/home/username/laravel-app
    - cd $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan db:seed --force
    - php artisan storage:link
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - chmod -R 775 storage bootstrap/cache